language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - v9
  - v8
  - v6
before_install:
  - npm install -g coveralls
install:
  - yarn install --ignore-engines --check-files
script:
  - npm run test:lint
  - npm run test:coverage
after_success:
  - cat ./coverage/lcov.info | coveralls || echo 'Failed to upload to coveralls...'
  - npm run semantic-release
